import type {Metadata} from "next";
import React from "react";

import "./globals.css";
import MenuComponent from "@/app/components/menu-container/MenuComponent";

export const metadata: Metadata = {
    title: "HomeLayout",
    description: "Generated by create next app",
};

type Props = { children: React.ReactNode };

export default function RootLayout({children}: Readonly<Props>) {
    return (
        <html lang="en">
        <body>
        <MenuComponent/>
        {children}
        </body>
        </html>
    );
}
